name: Automate LinkedIn Connection Requests

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv

      - name: Run Selenium script
        env:
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          # Start X Virtual Framebuffer
          Xvfb :99 &
          export DISPLAY=:99

          # Run the script
          python main.py

      # Optional: Upload logs or screenshots if the script fails
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: linkedin-automation-logs
          path: |
            ./*.png
            ./*.log